# Generated by Django 3.1.7 on 2021-02-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='billingprofile',
            managers=[
            ],
        ),
    ]
