# Generated by Django 3.1.6 on 2021-03-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='billingprofile',
            managers=[
            ],
        ),
    ]
