# Generated by Django 3.1.5 on 2021-02-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_billing'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.DeleteModel(
            name='BillingProfile',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
