# Generated by Django 3.1.7 on 2021-02-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timefield',
            field=models.TextField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
