# Generated by Django 3.1.5 on 2021-02-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_billing',
        ),
    ]
