# Generated by Django 3.1.6 on 2021-02-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_price',
            new_name='product_price',
        ),
    ]
