# Generated by Django 3.1.6 on 2021-02-06 09:56

import django.core.files.storage
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210205_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Lenovo\\Desktop\\SecondStagePragmatech\\My_Ecommerce_Project\\ecommerce\\media'), upload_to=product.models.upload_product_file_loc),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.BooleanField(default=False),
        ),
    ]
