# Generated by Django 3.1.5 on 2021-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverify',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
