# Generated by Django 3.1.6 on 2021-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0004_subcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cat_slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='subcat_slug',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='brands',
            field=models.ManyToManyField(related_name='subcategory_brands', to='brand.Brand'),
        ),
    ]
